//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://rpc.meh.es/regcon2/esquemas2019", IsNullable=false)]
public partial class dgp_declaracion {
    
    private dgp_declaracionCabecera cabeceraField;
    
    private dgp_declaracionEnteContratante enteContratanteField;
    
    private string anioField;
    
    /// <remarks/>
    public dgp_declaracionCabecera cabecera {
        get {
            return this.cabeceraField;
        }
        set {
            this.cabeceraField = value;
        }
    }
    
    /// <remarks/>
    public dgp_declaracionEnteContratante enteContratante {
        get {
            return this.enteContratanteField;
        }
        set {
            this.enteContratanteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="gYear")]
    public string anio {
        get {
            return this.anioField;
        }
        set {
            this.anioField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public partial class dgp_declaracionCabecera {
    
    private dgp_declaracionCabeceraUsuario usuarioField;
    
    private string registrosEnviadosField;
    
    private string tipoAdminField;
    
    private string tipoAdminLocalField;
    
    /// <remarks/>
    public dgp_declaracionCabeceraUsuario usuario {
        get {
            return this.usuarioField;
        }
        set {
            this.usuarioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
    public string RegistrosEnviados {
        get {
            return this.registrosEnviadosField;
        }
        set {
            this.registrosEnviadosField = value;
        }
    }
    
    /// <remarks/>
    public string tipoAdmin {
        get {
            return this.tipoAdminField;
        }
        set {
            this.tipoAdminField = value;
        }
    }
    
    /// <remarks/>
    public string tipoAdminLocal {
        get {
            return this.tipoAdminLocalField;
        }
        set {
            this.tipoAdminLocalField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public partial class dgp_declaracionCabeceraUsuario {
    
    private string dniField;
    
    private string nombreField;
    
    private string apellido1Field;
    
    private string apellido2Field;
    
    private string cargoField;
    
    private string direccionField;
    
    private string provinciaField;
    
    private string municipioField;
    
    private string codPostalField;
    
    private string telefonoField;
    
    private string faxField;
    
    private string mailField;
    
    /// <remarks/>
    public string dni {
        get {
            return this.dniField;
        }
        set {
            this.dniField = value;
        }
    }
    
    /// <remarks/>
    public string nombre {
        get {
            return this.nombreField;
        }
        set {
            this.nombreField = value;
        }
    }
    
    /// <remarks/>
    public string apellido1 {
        get {
            return this.apellido1Field;
        }
        set {
            this.apellido1Field = value;
        }
    }
    
    /// <remarks/>
    public string apellido2 {
        get {
            return this.apellido2Field;
        }
        set {
            this.apellido2Field = value;
        }
    }
    
    /// <remarks/>
    public string cargo {
        get {
            return this.cargoField;
        }
        set {
            this.cargoField = value;
        }
    }
    
    /// <remarks/>
    public string direccion {
        get {
            return this.direccionField;
        }
        set {
            this.direccionField = value;
        }
    }
    
    /// <remarks/>
    public string provincia {
        get {
            return this.provinciaField;
        }
        set {
            this.provinciaField = value;
        }
    }
    
    /// <remarks/>
    public string municipio {
        get {
            return this.municipioField;
        }
        set {
            this.municipioField = value;
        }
    }
    
    /// <remarks/>
    public string codPostal {
        get {
            return this.codPostalField;
        }
        set {
            this.codPostalField = value;
        }
    }
    
    /// <remarks/>
    public string telefono {
        get {
            return this.telefonoField;
        }
        set {
            this.telefonoField = value;
        }
    }
    
    /// <remarks/>
    public string fax {
        get {
            return this.faxField;
        }
        set {
            this.faxField = value;
        }
    }
    
    /// <remarks/>
    public string mail {
        get {
            return this.mailField;
        }
        set {
            this.mailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public partial class dgp_declaracionEnteContratante {
    
    private string codEnteContratanteField;
    
    private string nombreEnteContratanteField;
    
    private string nIFField;
    
    private dgp_declaracionEnteContratanteDepartamento[] departamentoField;
    
    /// <remarks/>
    public string codEnteContratante {
        get {
            return this.codEnteContratanteField;
        }
        set {
            this.codEnteContratanteField = value;
        }
    }
    
    /// <remarks/>
    public string nombreEnteContratante {
        get {
            return this.nombreEnteContratanteField;
        }
        set {
            this.nombreEnteContratanteField = value;
        }
    }
    
    /// <remarks/>
    public string NIF {
        get {
            return this.nIFField;
        }
        set {
            this.nIFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("departamento")]
    public dgp_declaracionEnteContratanteDepartamento[] departamento {
        get {
            return this.departamentoField;
        }
        set {
            this.departamentoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public partial class dgp_declaracionEnteContratanteDepartamento {
    
    private string codigoDepartamentoField;
    
    private string nombreDepartamentoField;
    
    private string nIFField;
    
    private dgp_declaracionEnteContratanteDepartamentoOrganoContratante[] organoContratanteField;
    
    /// <remarks/>
    public string codigoDepartamento {
        get {
            return this.codigoDepartamentoField;
        }
        set {
            this.codigoDepartamentoField = value;
        }
    }
    
    /// <remarks/>
    public string nombreDepartamento {
        get {
            return this.nombreDepartamentoField;
        }
        set {
            this.nombreDepartamentoField = value;
        }
    }
    
    /// <remarks/>
    public string NIF {
        get {
            return this.nIFField;
        }
        set {
            this.nIFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("organoContratante")]
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratante[] organoContratante {
        get {
            return this.organoContratanteField;
        }
        set {
            this.organoContratanteField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public partial class dgp_declaracionEnteContratanteDepartamentoOrganoContratante {
    
    private string codigoOrganoContratanteField;
    
    private string nombreOrganoContratanteField;
    
    private string nIFField;
    
    private dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContrato[] contratoField;
    
    /// <remarks/>
    public string codigoOrganoContratante {
        get {
            return this.codigoOrganoContratanteField;
        }
        set {
            this.codigoOrganoContratanteField = value;
        }
    }
    
    /// <remarks/>
    public string nombreOrganoContratante {
        get {
            return this.nombreOrganoContratanteField;
        }
        set {
            this.nombreOrganoContratanteField = value;
        }
    }
    
    /// <remarks/>
    public string NIF {
        get {
            return this.nIFField;
        }
        set {
            this.nIFField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contrato")]
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContrato[] contrato {
        get {
            return this.contratoField;
        }
        set {
            this.contratoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public partial class dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContrato {
    
    private string tipoContratoField;
    
    private string provinciaField;
    
    private string modalidadField;
    
    private string objetoField;
    
    private dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoCPV cPVField;
    
    private string caracteristicaBienesField;
    
    private dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoPreciosUnitarios[] preciosUnitariosField;
    
    private dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoConPorLotes conPorLotesField;
    
    private bool conPorLotesFieldSpecified;
    
    private dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoConMixto conMixtoField;
    
    private dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoConMarco conMarcoField;
    
    private dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoComplementario complementarioField;
    
    private dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoPublicidad publicidadField;
    
    private System.DateTime anuncioBoeField;
    
    private bool anuncioBoeFieldSpecified;
    
    private System.DateTime anuncioDOUEField;
    
    private bool anuncioDOUEFieldSpecified;
    
    private System.DateTime anuncioBocaField;
    
    private bool anuncioBocaFieldSpecified;
    
    private System.DateTime anuncioBopField;
    
    private bool anuncioBopFieldSpecified;
    
    private System.DateTime anuncioPerfilContratanteField;
    
    private bool anuncioPerfilContratanteFieldSpecified;
    
    private System.DateTime anuncioPrensaField;
    
    private bool anuncioPrensaFieldSpecified;
    
    private System.DateTime anuncioInternetField;
    
    private bool anuncioInternetFieldSpecified;
    
    private string tramiteField;
    
    private string procedimientoAdjudField;
    
    private string procNegArticuloField;
    
    private string procNegSubapartadoField;
    
    private string procNegCausaField;
    
    private string invitacionesField;
    
    private string formaAdjudField;
    
    private string importePresupuestoField;
    
    private string plazoField;
    
    private string plazoConcesionField;
    
    private dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoPlurianual plurianualField;
    
    private dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoAnualidad[] anualidadField;
    
    private dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoRevisionPrecios revisionPreciosField;
    
    private string formulaTipoField;
    
    private dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoClasificacionExigida[] clasificacionExigidaField;
    
    private dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoContratista[] contratistaField;
    
    private string paisOrigenField;
    
    private System.DateTime fechaAdjudicacionField;
    
    private string importeAdjudicacionField;
    
    private dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoEsIngreso esIngresoField;
    
    private string modalidadImporteField;
    
    private string valorModalidadField;
    
    private string unidadModalidadField;
    
    private string aportacionAdministracionField;
    
    private string iVAimporteAdjudicacionField;
    
    private string modalidadDeterminacionPrecioField;
    
    private System.DateTime fechaFormalizacionField;
    
    private System.DateTime fechaFinalizacionField;
    
    private bool fechaFinalizacionFieldSpecified;
    
    private string observacionesField;
    
    private string numeroField;
    
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContrato() {
        this.conMixtoField = dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoConMixto.no;
        this.conMarcoField = dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoConMarco.no;
        this.complementarioField = dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoComplementario.no;
        this.publicidadField = dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoPublicidad.no;
        this.plurianualField = dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoPlurianual.no;
        this.revisionPreciosField = dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoRevisionPrecios.no;
        this.paisOrigenField = "es";
        this.esIngresoField = dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoEsIngreso.no;
    }
    
    /// <remarks/>
    public string tipoContrato {
        get {
            return this.tipoContratoField;
        }
        set {
            this.tipoContratoField = value;
        }
    }
    
    /// <remarks/>
    public string provincia {
        get {
            return this.provinciaField;
        }
        set {
            this.provinciaField = value;
        }
    }
    
    /// <remarks/>
    public string modalidad {
        get {
            return this.modalidadField;
        }
        set {
            this.modalidadField = value;
        }
    }
    
    /// <remarks/>
    public string objeto {
        get {
            return this.objetoField;
        }
        set {
            this.objetoField = value;
        }
    }
    
    /// <remarks/>
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoCPV CPV {
        get {
            return this.cPVField;
        }
        set {
            this.cPVField = value;
        }
    }
    
    /// <remarks/>
    public string caracteristicaBienes {
        get {
            return this.caracteristicaBienesField;
        }
        set {
            this.caracteristicaBienesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("preciosUnitarios")]
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoPreciosUnitarios[] preciosUnitarios {
        get {
            return this.preciosUnitariosField;
        }
        set {
            this.preciosUnitariosField = value;
        }
    }
    
    /// <remarks/>
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoConPorLotes conPorLotes {
        get {
            return this.conPorLotesField;
        }
        set {
            this.conPorLotesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool conPorLotesSpecified {
        get {
            return this.conPorLotesFieldSpecified;
        }
        set {
            this.conPorLotesFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoConMixto.no)]
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoConMixto conMixto {
        get {
            return this.conMixtoField;
        }
        set {
            this.conMixtoField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoConMarco.no)]
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoConMarco conMarco {
        get {
            return this.conMarcoField;
        }
        set {
            this.conMarcoField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoComplementario.no)]
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoComplementario complementario {
        get {
            return this.complementarioField;
        }
        set {
            this.complementarioField = value;
        }
    }
    
    /// <remarks/>
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoPublicidad publicidad {
        get {
            return this.publicidadField;
        }
        set {
            this.publicidadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime anuncioBoe {
        get {
            return this.anuncioBoeField;
        }
        set {
            this.anuncioBoeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool anuncioBoeSpecified {
        get {
            return this.anuncioBoeFieldSpecified;
        }
        set {
            this.anuncioBoeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime anuncioDOUE {
        get {
            return this.anuncioDOUEField;
        }
        set {
            this.anuncioDOUEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool anuncioDOUESpecified {
        get {
            return this.anuncioDOUEFieldSpecified;
        }
        set {
            this.anuncioDOUEFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime anuncioBoca {
        get {
            return this.anuncioBocaField;
        }
        set {
            this.anuncioBocaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool anuncioBocaSpecified {
        get {
            return this.anuncioBocaFieldSpecified;
        }
        set {
            this.anuncioBocaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime anuncioBop {
        get {
            return this.anuncioBopField;
        }
        set {
            this.anuncioBopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool anuncioBopSpecified {
        get {
            return this.anuncioBopFieldSpecified;
        }
        set {
            this.anuncioBopFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime anuncioPerfilContratante {
        get {
            return this.anuncioPerfilContratanteField;
        }
        set {
            this.anuncioPerfilContratanteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool anuncioPerfilContratanteSpecified {
        get {
            return this.anuncioPerfilContratanteFieldSpecified;
        }
        set {
            this.anuncioPerfilContratanteFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime anuncioPrensa {
        get {
            return this.anuncioPrensaField;
        }
        set {
            this.anuncioPrensaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool anuncioPrensaSpecified {
        get {
            return this.anuncioPrensaFieldSpecified;
        }
        set {
            this.anuncioPrensaFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime anuncioInternet {
        get {
            return this.anuncioInternetField;
        }
        set {
            this.anuncioInternetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool anuncioInternetSpecified {
        get {
            return this.anuncioInternetFieldSpecified;
        }
        set {
            this.anuncioInternetFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string tramite {
        get {
            return this.tramiteField;
        }
        set {
            this.tramiteField = value;
        }
    }
    
    /// <remarks/>
    public string procedimientoAdjud {
        get {
            return this.procedimientoAdjudField;
        }
        set {
            this.procedimientoAdjudField = value;
        }
    }
    
    /// <remarks/>
    public string procNegArticulo {
        get {
            return this.procNegArticuloField;
        }
        set {
            this.procNegArticuloField = value;
        }
    }
    
    /// <remarks/>
    public string procNegSubapartado {
        get {
            return this.procNegSubapartadoField;
        }
        set {
            this.procNegSubapartadoField = value;
        }
    }
    
    /// <remarks/>
    public string procNegCausa {
        get {
            return this.procNegCausaField;
        }
        set {
            this.procNegCausaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
    public string invitaciones {
        get {
            return this.invitacionesField;
        }
        set {
            this.invitacionesField = value;
        }
    }
    
    /// <remarks/>
    public string formaAdjud {
        get {
            return this.formaAdjudField;
        }
        set {
            this.formaAdjudField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
    public string importePresupuesto {
        get {
            return this.importePresupuestoField;
        }
        set {
            this.importePresupuestoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
    public string plazo {
        get {
            return this.plazoField;
        }
        set {
            this.plazoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
    public string plazoConcesion {
        get {
            return this.plazoConcesionField;
        }
        set {
            this.plazoConcesionField = value;
        }
    }
    
    /// <remarks/>
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoPlurianual plurianual {
        get {
            return this.plurianualField;
        }
        set {
            this.plurianualField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("anualidad")]
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoAnualidad[] anualidad {
        get {
            return this.anualidadField;
        }
        set {
            this.anualidadField = value;
        }
    }
    
    /// <remarks/>
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoRevisionPrecios revisionPrecios {
        get {
            return this.revisionPreciosField;
        }
        set {
            this.revisionPreciosField = value;
        }
    }
    
    /// <remarks/>
    public string formulaTipo {
        get {
            return this.formulaTipoField;
        }
        set {
            this.formulaTipoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("clasificacionExigida")]
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoClasificacionExigida[] clasificacionExigida {
        get {
            return this.clasificacionExigidaField;
        }
        set {
            this.clasificacionExigidaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("contratista")]
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoContratista[] contratista {
        get {
            return this.contratistaField;
        }
        set {
            this.contratistaField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute("es")]
    public string paisOrigen {
        get {
            return this.paisOrigenField;
        }
        set {
            this.paisOrigenField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime fechaAdjudicacion {
        get {
            return this.fechaAdjudicacionField;
        }
        set {
            this.fechaAdjudicacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
    public string importeAdjudicacion {
        get {
            return this.importeAdjudicacionField;
        }
        set {
            this.importeAdjudicacionField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute(dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoEsIngreso.no)]
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoEsIngreso esIngreso {
        get {
            return this.esIngresoField;
        }
        set {
            this.esIngresoField = value;
        }
    }
    
    /// <remarks/>
    public string modalidadImporte {
        get {
            return this.modalidadImporteField;
        }
        set {
            this.modalidadImporteField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
    public string valorModalidad {
        get {
            return this.valorModalidadField;
        }
        set {
            this.valorModalidadField = value;
        }
    }
    
    /// <remarks/>
    public string unidadModalidad {
        get {
            return this.unidadModalidadField;
        }
        set {
            this.unidadModalidadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
    public string aportacionAdministracion {
        get {
            return this.aportacionAdministracionField;
        }
        set {
            this.aportacionAdministracionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
    public string IVAimporteAdjudicacion {
        get {
            return this.iVAimporteAdjudicacionField;
        }
        set {
            this.iVAimporteAdjudicacionField = value;
        }
    }
    
    /// <remarks/>
    public string modalidadDeterminacionPrecio {
        get {
            return this.modalidadDeterminacionPrecioField;
        }
        set {
            this.modalidadDeterminacionPrecioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime fechaFormalizacion {
        get {
            return this.fechaFormalizacionField;
        }
        set {
            this.fechaFormalizacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime fechaFinalizacion {
        get {
            return this.fechaFinalizacionField;
        }
        set {
            this.fechaFinalizacionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool fechaFinalizacionSpecified {
        get {
            return this.fechaFinalizacionFieldSpecified;
        }
        set {
            this.fechaFinalizacionFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string observaciones {
        get {
            return this.observacionesField;
        }
        set {
            this.observacionesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numero {
        get {
            return this.numeroField;
        }
        set {
            this.numeroField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public partial class dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoCPV {
    
    private string codigoCPVField;
    
    private string versionField;
    
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoCPV() {
        this.versionField = "2008";
    }
    
    /// <remarks/>
    public string codigoCPV {
        get {
            return this.codigoCPVField;
        }
        set {
            this.codigoCPVField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public partial class dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoPreciosUnitarios {
    
    private dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoPreciosUnitariosCPV cPVField;
    
    private decimal precioUnitarioField;
    
    /// <remarks/>
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoPreciosUnitariosCPV CPV {
        get {
            return this.cPVField;
        }
        set {
            this.cPVField = value;
        }
    }
    
    /// <remarks/>
    public decimal precioUnitario {
        get {
            return this.precioUnitarioField;
        }
        set {
            this.precioUnitarioField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public partial class dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoPreciosUnitariosCPV {
    
    private string codigoCPVField;
    
    private string versionField;
    
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoPreciosUnitariosCPV() {
        this.versionField = "2008";
    }
    
    /// <remarks/>
    public string codigoCPV {
        get {
            return this.codigoCPVField;
        }
        set {
            this.codigoCPVField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public enum dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoConPorLotes {
    
    /// <remarks/>
    si,
    
    /// <remarks/>
    SI,
    
    /// <remarks/>
    NO,
    
    /// <remarks/>
    no,
    
    /// <remarks/>
    No,
    
    /// <remarks/>
    Si,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public enum dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoConMixto {
    
    /// <remarks/>
    si,
    
    /// <remarks/>
    SI,
    
    /// <remarks/>
    NO,
    
    /// <remarks/>
    no,
    
    /// <remarks/>
    No,
    
    /// <remarks/>
    Si,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public enum dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoConMarco {
    
    /// <remarks/>
    si,
    
    /// <remarks/>
    Si,
    
    /// <remarks/>
    SI,
    
    /// <remarks/>
    no,
    
    /// <remarks/>
    No,
    
    /// <remarks/>
    NO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public enum dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoComplementario {
    
    /// <remarks/>
    si,
    
    /// <remarks/>
    Si,
    
    /// <remarks/>
    SI,
    
    /// <remarks/>
    no,
    
    /// <remarks/>
    No,
    
    /// <remarks/>
    NO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public enum dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoPublicidad {
    
    /// <remarks/>
    si,
    
    /// <remarks/>
    Si,
    
    /// <remarks/>
    SI,
    
    /// <remarks/>
    no,
    
    /// <remarks/>
    No,
    
    /// <remarks/>
    NO,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public enum dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoPlurianual {
    
    /// <remarks/>
    no,
    
    /// <remarks/>
    No,
    
    /// <remarks/>
    NO,
    
    /// <remarks/>
    si,
    
    /// <remarks/>
    Si,
    
    /// <remarks/>
    SI,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public partial class dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoAnualidad {
    
    private string anioField;
    
    private string importeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="gYear")]
    public string anio {
        get {
            return this.anioField;
        }
        set {
            this.anioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
    public string importe {
        get {
            return this.importeField;
        }
        set {
            this.importeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public enum dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoRevisionPrecios {
    
    /// <remarks/>
    no,
    
    /// <remarks/>
    No,
    
    /// <remarks/>
    NO,
    
    /// <remarks/>
    si,
    
    /// <remarks/>
    Si,
    
    /// <remarks/>
    SI,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public partial class dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoClasificacionExigida {
    
    private string grupoField;
    
    private string subgrupoField;
    
    private string categoriaField;
    
    /// <remarks/>
    public string grupo {
        get {
            return this.grupoField;
        }
        set {
            this.grupoField = value;
        }
    }
    
    /// <remarks/>
    public string subgrupo {
        get {
            return this.subgrupoField;
        }
        set {
            this.subgrupoField = value;
        }
    }
    
    /// <remarks/>
    public string categoria {
        get {
            return this.categoriaField;
        }
        set {
            this.categoriaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public partial class dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoContratista {
    
    private string descripcionField;
    
    private string nacionalidadField;
    
    private string nifField;
    
    public dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoContratista() {
        this.nacionalidadField = "es";
    }
    
    /// <remarks/>
    public string descripcion {
        get {
            return this.descripcionField;
        }
        set {
            this.descripcionField = value;
        }
    }
    
    /// <remarks/>
    [System.ComponentModel.DefaultValueAttribute("es")]
    public string nacionalidad {
        get {
            return this.nacionalidadField;
        }
        set {
            this.nacionalidadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nif {
        get {
            return this.nifField;
        }
        set {
            this.nifField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://rpc.meh.es/regcon2/esquemas2019")]
public enum dgp_declaracionEnteContratanteDepartamentoOrganoContratanteContratoEsIngreso {
    
    /// <remarks/>
    no,
    
    /// <remarks/>
    No,
    
    /// <remarks/>
    NO,
    
    /// <remarks/>
    si,
    
    /// <remarks/>
    Si,
    
    /// <remarks/>
    SI,
}
